package com.myspace.dmnstructtypes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String custName;

	public Customer() {
	}

	public java.lang.String getCustName() {
		return this.custName;
	}

	public void setCustName(java.lang.String custName) {
		this.custName = custName;
	}

	public Customer(java.lang.String custName) {
		this.custName = custName;
	}

}