package com.myspace.dmnstructtypes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String employeeId;

	private java.lang.Integer experience;

	private java.lang.Integer level;

	public Employee() {
	}

	public java.lang.String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(java.lang.String employeeId) {
		this.employeeId = employeeId;
	}

	public java.lang.Integer getExperience() {
		return this.experience;
	}

	public void setExperience(java.lang.Integer experience) {
		this.experience = experience;
	}

	public java.lang.Integer getLevel() {
		return this.level;
	}

	public void setLevel(java.lang.Integer level) {
		this.level = level;
	}

	public Employee(java.lang.String employeeId, java.lang.Integer experience,
			java.lang.Integer level) {
		this.employeeId = employeeId;
		this.experience = experience;
		this.level = level;
	}

}